#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib"; unshift @INC, "$FindBin::Bin/../../Mojolicious-Plugin-Admin/lib"; }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('CMS');
