#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib"; unshift @INC, "$FindBin::Bin/../../Mojolicious-Plugin-GG/lib"; }
use Mojolicious::Commands;
# die join("\n", @INC);
# Start command line interface for application
Mojolicious::Commands->start_app('CMS');
